test -e work || vlib work 
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../rtl/verilog /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../rtl/verilog/Decode_Pipelined.vp
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE   +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/uvmf_installation/uvmf_base_pkg -F /mnt/ncsudrive/t/tkulkar/ECE748/uvmf_installation/uvmf_base_pkg/uvmf_base_pkg_filelist_hdl.f
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE   +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/uvmf_installation/uvmf_base_pkg -F /mnt/ncsudrive/t/tkulkar/ECE748/uvmf_installation/uvmf_base_pkg/uvmf_base_pkg_filelist_hvl.f
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_in_pkg -F /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_in_pkg/decode_in_filelist_hdl.f 
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_in_pkg -F /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_in_pkg/decode_in_filelist_hvl.f 
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_in_pkg -F /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_in_pkg/decode_in_filelist_xrtl.f  
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_out_pkg -F /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_out_pkg/decode_out_filelist_hdl.f 
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_out_pkg -F /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_out_pkg/decode_out_filelist_hvl.f 
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_out_pkg -F /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/interface_packages/decode_out_pkg/decode_out_filelist_xrtl.f  
vlog /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../../../verification_ip/environment_packages/decode_env_pkg/decode_env_pkg.sv \

vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../tb/tests /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../tb/tests/decode_test_pkg/decode_test_pkg.sv
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/questa_mvc_src/sv +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../tb/testbench -F /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../tb/testbench/top_filelist_hvl.f
vlog -sv -suppress 2223 -suppress 2286 -covermultiuserenv   +define+UVM_REPORT_DISABLE_FILE_LINE +define+UVM_REPORT_DISABLE_FILE_LINE  +incdir+/mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../tb/testbench -F /mnt/ncsudrive/t/tkulkar/ECE748/tkulkar_p2a/project_benches/decode/sim/../tb/testbench/top_filelist_hdl.f
vopt       hvl_top hdl_top    -o optimized_batch_top_tb
vopt    +acc    hvl_top hdl_top    -o optimized_debug_top_tb
vsim -i    -sv_seed 1 +UVM_TESTNAME=test_top  -permit_unmatched_virtual_intf +notimingchecks -suppress 8887 -solvefaildebug -solvefailtestcase    -assertdebug -uvmcontrol=all +uvm_set_config_int=*,enable_transaction_viewing,1 -classdebug -title test_top -msgmode tran    -do " set NoQuitOnFinish 1; run 0; do wave.do "  optimized_debug_top_tb 
