uvmf:
  environments:
    memaccess:
      agents:
      - initiator_responder: RESPONDER
        name: memaccess_in
        type: memaccess_in
      - initiator_responder: RESPONDER
        name: memaccess_out
        type: memaccess_out
      analysis_components:
      - name: memaccess_predictor
        parameters: []
        type: memaccess_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: memaccess_scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: memaccess_out_transaction
      subenvs: []
      tlm_connections:
      - driver: memaccess_in.monitored_ap
        receiver: memaccess_predictor.memaccess_predictor_analysis_export
        validate: 'True'
      - driver: memaccess_predictor.memaccess_predictor_analysis_port
        receiver: memaccess_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: memaccess_out.monitored_ap
        receiver: memaccess_scoreboard.actual_analysis_export
        validate: 'True'
