uvmf:
  environments:
    writeback:
      agents:
      - initiator_responder: INITIATOR
        name: writeback_in
        type: writeback_in
      - initiator_responder: RESPONDER
        name: writeback_out
        type: writeback_out
      analysis_components:
      - name: writeback_predictor
        parameters: []
        type: writeback_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'False'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: writeback_scoreboard
        sb_type: uvmf_in_order_scoreboard
        trans_type: writeback_out_transaction
      subenvs: []
      tlm_connections:
      - driver: writeback_in.monitored_ap
        receiver: writeback_predictor.writeback_predictor_analysis_export
        validate: 'True'
      - driver: writeback_predictor.writeback_predictor_analysis_port
        receiver: writeback_scoreboard.expected_analysis_export
        validate: 'True'
      - driver: writeback_out.monitored_ap
        receiver: writeback_scoreboard.actual_analysis_export
        validate: 'True'
  
  util_components:
    writeback_predictor:
      analysis_exports:
      - name: writeback_predictor_analysis_export
        type: writeback_in_transaction
      analysis_ports:
      - name: writeback_predictor_analysis_port
        type: writeback_out_transaction
      existing_library_component: 'False'
      type: predictor