uvmf:
  environments:
    control:
      agents:
      - initiator_responder: INITIATOR
        name: control_in_agent_inst
        type: control_in
      - initiator_responder: RESPONDER
        name: control_out_agent_inst
        type: control_out
      analysis_components:
      - name: control_predictor_inst
        parameters: []
        type: control_predictor
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards:
      - name: control_scoreboard_inst
        sb_type: uvmf_in_order_race_scoreboard
        trans_type: control_out_transaction
      subenvs: []
      tlm_connections:
      - driver: control_in_agent_inst.monitored_ap
        receiver: control_predictor_inst.analysis_export
        validate: 'True'
      - driver: control_predictor_inst.control_predictor_inst_ap
        receiver: control_scoreboard_inst.expected_analysis_export
        validate: 'True'
      - driver: control_out_agent_inst.monitored_ap
        receiver: control_scoreboard_inst.actual_analysis_export
        validate: 'True'
